name: qt_viz_tests
on:
    pull_request:
    push:
      branches: main

jobs:
  raw-viz-tests:
    runs-on: ubuntu-latest
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
#        qt-version: [PyQt5, PySide2]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: Install PySide2
#        if: matrix.qt-version == 'PySide2'
#        run: |
#          python -m pip uninstall PyQt5 -y
#          python -m pip install PySide2
      - name: Lint with flake8
        run: flake8
      - name: Test pwd
        run: pwd
      - name: Run MNE-Tests
        run: |
          pwd
          mnePath=$(python -c "import mne; print(mne.__path__[0])")
          mkdir ./_temp_tests
          cp $mnePath/viz/tests/test_raw.py ./_temp_tests/test_raw.py
          pytest
          rm -r ./_temp_tests
        shell: bash